source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/sportradar/SR_AVVPlayer_iOS.git'

platform :ios, '11.0'
use_frameworks!

target 'SR_AVVPlayer_Example' do

#ImageCache
pod 'AVVPlayer-MARVIN', '0.9.9'
end
